version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEB3_PROVIDER_URI=${WEB3_PROVIDER_URI}
    volumes:
      - ./.env:/app/.env
    restart: unless-stopped
